### ISSUE TITLE
Issues with v2.8.0 pre-commit

### ISSUE THREAD

**Issue by CompRhys** [omnilib/ufmt#251]
```
repos:
-   repo: https://github.com/omnilib/ufmt
    rev: v2.8.0
    hooks:
    -   id: ufmt
        additional_dependencies:
        - black>=24.1.1
        - usort>=1.0.7
        args: [format]

```

the above `pre-commit-config.yaml` results in the errors: 
```
Error formatting /Users/user/botorch/test/utils/test_sampling.py: name 'ruff_api' is not defined
✨ 401 errors ✨
```

Running the same with `rev: v2.3.0` works but any later revisions give this error.

**Comment by CompRhys** [comment]
```
-   repo: https://github.com/omnilib/ufmt
    name: ufmt
    rev: v2.8.0
    hooks:
    -   id: ufmt
        additional_dependencies:
        - black==24.4.2
        - usort==1.0.8.post1
        - ruff-api
        args: [format]
```

The simple change to install ruff-api fixes the pre-commit.
