### ISSUE TITLE
allow Black formatting option as pre-commit arg

### ISSUE THREAD

**Issue by Borda** [omnilib/ufmt#48]
Hi there,
I found this very handy aggregation of the two most used formatting tools.
Not sure if it is already feasible (if so would be nice to have it mentioned in readme) but it would be great to allow passing Black arguments such as line length `--line-length=120`. I have tried naive way but does not work
```yaml
  - repo: https://github.com/omnilib/ufmt
    rev: v1.3.0
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 21.9b0
          - usort == 0.6.4
        args: ["--line-length=120"]
```
